apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: afsc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: afpv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: afsc
  awsElasticBlockStore:
    volumeID: vol-0110bd3c1e3461570
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-pvc
spec:
  storageClassName: afsc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi     